export const testList = [
    {
        testName: 'Complete Blood Count (CBC)',
        rate: 250,
        category: 'Hematology',
        tube: 'EDTA (Purple Top)',
    },
    {
        testName: 'Erythrocyte Sedimentation Rate (ESR)',
        rate: 200,
        category: 'Hematology',
        tube: 'EDTA (Purple Top)',
    },
    {
        testName: 'Blood Glucose (Fasting)',
        rate: 150,
        category: 'Biochemistry',
        tube: 'Fluoride (Gray Top)',
    },
    {
        testName: 'Blood Glucose (Postprandial)',
        rate: 150,
        category: 'Biochemistry',
        tube: 'Fluoride (Gray Top)',
    },
    {
        testName: 'Liver Function Test (LFT)',
        rate: 600,
        category: 'Biochemistry',
        tube: 'Serum (Red/Yellow Top)',
    },
    {
        testName: 'Kidney Function Test (KFT)',
        rate: 700,
        category: 'Biochemistry',
        tube: 'Serum (Red/Yellow Top)',
    },
    {
        testName: 'Lipid Profile',
        rate: 800,
        category: 'Biochemistry',
        tube: 'Serum (Red/Yellow Top)',
    },
    {
        testName: 'Thyroid Profile (T3, T4, TSH)',
        rate: 500,
        category: 'Endocrinology',
        tube: 'Serum (Red/Yellow Top)',
    },
    {
        testName: 'HbA1c (Glycated Hemoglobin)',
        rate: 400,
        category: 'Biochemistry',
        tube: 'EDTA (Purple Top)',
    },
    {
        testName: 'Urine Routine & Microscopy',
        rate: 150,
        category: 'Urine Analysis',
        tube: 'Sterile Urine Container',
    },
    {
        testName: 'Serum Calcium',
        rate: 250,
        category: 'Biochemistry',
        tube: 'Serum (Red/Yellow Top)',
    },
    {
        testName: 'Serum Vitamin D (25-OH)',
        rate: 1200,
        category: 'Vitamins',
        tube: 'Serum (Red/Yellow Top)',
    },
    {
        testName: 'Serum Vitamin B12',
        rate: 1000,
        category: 'Vitamins',
        tube: 'Serum (Red/Yellow Top)',
    },
    {
        testName: 'Hepatitis B Surface Antigen (HBsAg)',
        rate: 400,
        category: 'Serology',
        tube: 'Serum (Red/Yellow Top)',
    },
    {
        testName: 'HIV 1 & 2 Antibody Test',
        rate: 500,
        category: 'Serology',
        tube: 'Serum (Red/Yellow Top)',
    },
    {
        testName: 'Dengue NS1 Antigen',
        rate: 600,
        category: 'Serology',
        tube: 'Serum (Red/Yellow Top)',
    },
    {
        testName: 'COVID-19 RT-PCR',
        rate: 1200,
        category: 'Molecular Biology',
        tube: 'Nasopharyngeal Swab (VTM)',
    },
    {
        testName: 'Malaria Parasite (MP) Smear',
        rate: 300,
        category: 'Parasitology',
        tube: 'EDTA (Purple Top)',
    },
    {
        testName: 'C-Reactive Protein (CRP)',
        rate: 400,
        category: 'Biochemistry/Immunology',
        tube: 'Serum (Red/Yellow Top)',
    },
    {
        testName: 'Prothrombin Time (PT/INR)',
        rate: 350,
        category: 'Coagulation',
        tube: 'Citrate (Blue Top)',
    },
];
